sudo: false
language: node_js
branches:
  only:
    - master # trigger release only for PRs and changes pushed to master branch
notifications:
  email: false
node_js:
  - '12'
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
after_success:
  - yarn semantic-release
